"""Effect (mode) names for MELK Light Bar.

Extracted from the decompiled Android app resources:
`resources/res/values/arrays.xml` (modes_group* + modes_group*_command).
"""

from __future__ import annotations

# name -> mode number (sent as CMD 0x03 data0)
MELK_EFFECTS: dict[str, int] = {
    "Magic Forward": 1,
    "Sunrise": 1,
    "Magic Back": 2,
    "Sunset": 2,
    "7-Color Trans": 3,
    "Birthday": 3,
    "7-Color Trans Back": 4,
    "Candlelight": 4,
    "Fireworks": 5,
    "R-G-B Trans": 5,
    "Party": 6,
    "R-G-B Trans Back": 6,
    "Datiny": 7,
    "Y-C-P Trans": 7,
    "Starry sky": 8,
    "Y-C-P Trans Back": 8,
    "6-Color to Red": 9,
    "Romantic": 9,
    "6-Color to Red Back": 10,
    "Disco": 10,
    "6-Color to Green": 11,
    "Rainbow": 11,
    "6-Color to Green Back": 12,
    "Movie": 12,
    "6-Color to Blue": 13,
    "Christmas": 13,
    "6-Color to Blue Back": 14,
    "Flowing": 14,
    "6-Color to Cyan": 15,
    "Sleeping": 15,
    "6-Color to Cyan Back": 16,
    "Ocean": 16,
    "6-Color to Yellow": 17,
    "Forest": 17,
    "6-Color to Yellow Back": 18,
    "Reading": 18,
    "6-Color to Purple": 19,
    "Working": 19,
    "6-Color to Purple Back": 20,
    "Dazzle": 20,
    "6-Color to White": 21,
    "Gentle": 21,
    "6-Color to White Back": 22,
    "Wedding": 22,
    "7-Color Tail": 23,
    "Snow": 23,
    "7-Color Tail Back": 24,
    "Fire": 24,
    "Lightning": 25,
    "Red Tail": 25,
    "Red Tail Back": 26,
    "Valentine's Day": 26,
    "Green Tail": 27,
    "Hallowmas": 27,
    "Green Tail Back": 28,
    "Warnning": 28,
    "Blue Tail": 29,
    "Blue Tail Back": 30,
    "Yellow Tail": 31,
    "Yellow Tail Back": 32,
    "Cyan Tail": 33,
    "Cyan Tail Back": 34,
    "Purple Tail": 35,
    "Purple Tail Back": 36,
    "White Tail": 37,
    "White Tail Back": 38,
    "7-Color Water": 39,
    "7-Color Water Back": 40,
    "R-G-B Water": 41,
    "R-G-B Water Back": 42,
    "Y-C-P Water": 43,
    "Y-C-P Water Back": 44,
    "R-G Water": 45,
    "R-G Water Back": 46,
    "G-B Water": 47,
    "G-B Water Back": 48,
    "Y-B Water": 49,
    "Y-B Water Back": 50,
    "Y-C Water": 51,
    "Y-C Water Back": 52,
    "C-P Water": 53,
    "C-P Water Back": 54,
    "White Water": 55,
    "White Water Back": 56,
    "7-Color Close": 57,
    "7-Color Open": 58,
    "R-G-B Close": 59,
    "R-G-B Open": 60,
    "Y-C-P Close": 61,
    "Y-C-P Open": 62,
    "Red Close": 63,
    "Red Open": 64,
    "Green Close": 65,
    "Green Open": 66,
    "Blue Close": 67,
    "Blue Open": 68,
    "Yellow Close": 69,
    "Yellow Open": 70,
    "Cyan Close": 71,
    "Cyan Open": 72,
    "Purple Close": 73,
    "Purple Open": 74,
    "White Close": 75,
    "White Open": 76,
    "7-Color Race": 77,
    "7-Color Race Back": 78,
    "R-G-B Race": 79,
    "R-G-B Race Back": 80,
    "Y-C-P Race": 81,
    "Y-C-P Race Back": 82,
    "7-Color Wave": 83,
    "7-Color Wave Back": 84,
    "R-G-B Wave": 85,
    "R-G-B Wave Back": 86,
    "Y-C-P Wave": 87,
    "Y-C-P Wave Back": 88,
    "Red Running": 89,
    "Red Run Back": 90,
    "Green Running": 91,
    "Green Run Back": 92,
    "Blue Running": 93,
    "Blue Run Back": 94,
    "Yellow Running": 95,
    "Yellow Run Back": 96,
    "Cyan Running": 97,
    "Cyan Run Back": 98,
    "Purple Running": 99,
    "Purple Run Back": 100,
    "White Running": 101,
    "White Run Back": 102,
    "7-Color Running": 103,
    "7-Color Run Back": 104,
    "R-G-B Running": 105,
    "R-G-B Run Back": 106,
    "Y-C-P Running": 107,
    "Y-C-P Run Back": 108,
    "B-P-C-Y Running": 109,
    "B-P-C-Y Run Back": 110,
    "B-G-C-Y Running": 111,
    "B-G-C-Y Run Back": 112,
    "Red-Dot in White Running": 113,
    "Red-Dot in White Run Back": 114,
    "Green-Dot in Red Running": 115,
    "Green-Dot in Red Run Back": 116,
    "Blue-Dot in Green Running": 117,
    "Blue-Dot in Green Run Back": 118,
    "Yellow-Dot in Blue Running": 119,
    "Yellow-Dot in Blue Run Back": 120,
    "Cyan-Dot in Yellow Running": 121,
    "Cyan-Dot in Yellow Run Back": 122,
    "Purple-Dot in Cyan Running": 123,
    "Purple-Dot in Cyan Run Back": 124,
    "White-Dot in Purple Running": 125,
    "White-Dot in Purple Run Back": 126,
    "White-Dot in Red Running": 127,
    "White-Dot in Red Run Back": 128,
    "7-Color in Red Running": 129,
    "7-Color in Red Run Back": 130,
    "7-Color in Green Running": 131,
    "7-Color in Green Run Back": 132,
    "7-Color in Blue Running": 133,
    "7-Color in Blue Run Back": 134,
    "7-Color in Yellow Running": 135,
    "7-Color in Yellow Run Back": 136,
    "7-Color in Cyan Running": 137,
    "7-Color in Cyan Run Back": 138,
    "7-Color in Purple Running": 139,
    "7-Color in Purple Run Back": 140,
    "7-Color in White Running": 141,
    "7-Color in White Run Back": 142,
    "W-R-W Flow": 143,
    "W-R-W Flow Back": 144,
    "W-G-W Flow": 145,
    "W-G-W Flow Back": 146,
    "W-B-W Flow": 147,
    "W-B-W Flow Back": 148,
    "W-Y-W Flow": 149,
    "W-Y-W Flow Back": 150,
    "W-C-W Flow": 151,
    "W-C-W Flow Back": 152,
    "W-P-W Flow": 153,
    "W-P-W Flow Back": 154,
    "R-W-R Flow": 155,
    "R-W-R Flow Back": 156,
    "G-W-G Flow": 157,
    "G-W-G Flow Back": 158,
    "B-W-B Flow": 159,
    "B-W-B Flow Back": 160,
    "Y-W-Y Flow": 161,
    "Y-W-Y Flow Back": 162,
    "C-W-C Flow": 163,
    "C-W-C Flow Back": 164,
    "P-W-P Flow": 165,
    "P-W-P Flow Back": 166,
    "Green-Dot in Blue Running": 167,
    "Green-Dot in Blue Run Back": 168,
    "Red-Dot in Blue Running": 171,
    "Red-Dot in Blue Run Back": 172,
    "Yellow-Dot in Purple Running": 175,
    "Yellow-Dot in Purple Run Back": 176,
    "White-Dot in Yelllow Running": 177,
    "White-Dot in Yelllow Run Back": 178,
    "Yellow-Dot in White Running": 179,
    "Yellow-Dot in White Run Back": 180,
    "7-Color Flush": 181,
    "7-Color Flush Back": 182,
    "R-G-B Flush": 183,
    "R-G-B Flush Back": 184,
    "Y-C-P Flush": 185,
    "Y-C-P Flush Back": 186,
    "7-Color Flush Close": 187,
    "7-Color Flush Open": 188,
    "R-G-B Flush Close": 189,
    "R-G-B Flush Open": 190,
    "Y-C-P Flush Close": 191,
    "Y-C-P Flush Open": 192,
    "7-Color Jump": 193,
    "R-G-B Jump": 194,
    "Y-C-P Jump": 195,
    "7-Color Strobe": 196,
    "R-G-B Strobe": 197,
    "Y-C-P Strobe": 198,
    "7-Color Gradual": 199,
    "R-Y Gradual": 200,
    "R-P Gradual": 201,
    "G-C Gradual": 202,
    "G-Y Gradual": 203,
    "B-P Gradual": 204,
    "Red Marquee": 205,
    "Green Marquee": 206,
    "Blue Marquee": 207,
    "Yellow Marquee": 208,
    "Cyan Marquee": 209,
    "Purple Marquee": 210,
    "White Marquee": 211,
    "7-Color Energy": 212,
}


def effect_name_from_mode(mode: int | None) -> str | None:
    """Pick a stable name for a mode number."""
    if mode is None:
        return None
    # Prefer the shortest name when multiple map to same command.
    names = [n for n, m in MELK_EFFECTS.items() if m == mode]
    if not names:
        return None
    return sorted(names, key=lambda s: (len(s), s.lower()))[0]

